SELECT
A.DEPT_ID,
B.DEPT_NAME_EN,
A.AVG_SAL
FROM
(SELECT
D.DEPT_ID,
ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES E
LEFT OUTER JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID) A
LEFT OUTER JOIN HR_DEPARTMENT B
ON A.DEPT_ID = B.DEPT_ID
ORDER BY 3 DESC